### ISSUE TITLE
[Question] Finding UserId

### ISSUE THREAD

**Issue by Liam31** [RbxAPI/Pyblox#15]
Is there a good way to get the UserId for further use? For example `Friends.friendList(randomid,1)`

**Comment by sbhadr** [comment]
A bit confused by the question if you don't mind rewording it. Also, the version of Pyblox you're using is severely out of date and will most likely fail. I haven't made any additions to correct this because I am in the process of rewriting the library. 

It's recommended that you use: https://github.com/RbxAPI/Pyblox/tree/nightly_build

Install it via the following:
``pip uninstall pyblox3``
``pip install pyblox3==3.0b4``

**Comment by Liam31** [comment]
I will reinstall the version, and what I mean is making a separate function to retrieve the userId for later use. There are ways to get Usernames and check if they exist, and I was curious if there is a way I can do that using Pyblox or Roblox API in general but for UserIds.

**Comment by sbhadr** [comment]
You'd need a collection of users to be able to get their ids. Typically, for groups, you can fetch each member in the group and page between and should provide a user id. Otherwise, it'll have to be manual unless you already know their username. 
i.e https://github.com/RbxAPI/Pyblox/blob/nightly_build/pyblox3/src/users.py#L28 , etc

To validate if the userid exists, you'd can do so with this method:
https://github.com/RbxAPI/Pyblox/blob/nightly_build/pyblox3/src/users.py#L28

If the user doesn't exist, it will return ``404`` as the error in the response body. 
Returns are tuples that follow the format of: statusCode (int), responseBody (json).

**Comment by Liam31** [comment]
Thank you for the clarification, it helped tremendously.
