### ISSUE TITLE
Groups.grouplist(userid) is returning None

### ISSUE THREAD

**Issue by envyaims** [RbxAPI/Pyblox#19]
So i'm coding a discord bot and I want it to display the names of all the groups a roblox user is in, however when I do the groupList function, it returns none. Here is my code:

        groups = pyblox3.Groups.groupList(userid)
        print(groups)

The response i get:
None
ERROR:root:[Pyblox][GET] Something went wrong. Error: 404

**Comment by sbhadr** [comment]
This is because, Roblox recently removed the api.roblox.com endpoints which is what that relied on. 

I’ve been working on an updated version for quite some time now. https://github.com/RbxAPI/Pyblox/tree/nightly_build

The method you’re looking for is under groups.

**Comment by envyaims** [comment]
How do i get the result i was looking for with the updated api? It returns a property object when I use RbxAPI.Users.groups.

**Comment by sbhadr** [comment]
There used to be a group-fetch that would return all groups the specified user was in. For some odd reason, I don't think this functionality exists. You can actually get around this by getting all the roles the specified user has for each group and just trace back to the group each role pertains to. 

Method Definition:
https://github.com/RbxAPI/Pyblox/blob/d1683f6fc9e0ea5410d40808dbefe135ab44ffba/pyblox3/src/groups.py#L268

Here's an example on how to use the groups API:
https://github.com/RbxAPI/Pyblox/blob/nightly_build/TESTFILE.py

Closing since base question / issue has been solved.
