### ISSUE TITLE
Error handling 

### ISSUE THREAD

**Issue by iranathan** [RbxAPI/Pyblox#9]
Hi, I think instead of using print to show that a request failed the lib should raise an error. 
Although the person is able to detect if the function worked by checking if it returned ``None`` or not there program is unable to get the reason without there being a human looking at the console.

If the lib would throw an error the program would be able to get why it failed with try/except statements, witch would be useful if someone is using the lib for public projects so they can display the error to the user.

```PY
response = await Groups_v1.Wall.post(groupid=4658962,body="Async Test 1")
if not response:
   print("failed")
```

```PY
from pyblox import RequestError

try:
   await Groups_v1.Wall.post(groupid=4658962,body="Async Test 1")
except RequestError as message:
   print("Failed", message")
```

Thanks, Ira.

**Comment by edwrddd** [comment]
good idea

**Comment by sbhadr** [comment]
The suggestion is quite nice and a planned thing for Pyblox. Unfortunately, I needed to manually test each error, so I wrote it out as a personal mission. Since Pyblox ``v3.x.x`` is still in pre-release, It's not as big as an issue as one might expect. However, this design is flawed as you stated and will be corrected in the next update/installment.

```python
from pyblox import RequestError

try:
   await Groups_v1.Wall.post(groupid=4658962,body="Async Test 1")
except RequestError as message:
   print("Failed", message")
```
As for your proposed syntax, I'd prefer to have fewer lines as possible to make integration smooth and fast. I'm not keen on having a bunch of external ``try-except`` statements and would rather keep this internal. 

Perhaps, something like this could work:
```python
 await Groups_v1.Wall.post(groupid=4658962,body="Async Test 1")
```

I've been working on condensing the base event loop that ``asyncio`` requires. 
```python
import asyncio # Won't be needed to import
import aiohttp # Won't be needed to import
from Pyblox.pyblox3 import Groups_v1

# Instance your group as a variable
base_group = Groups_v1(groupid="GROUPID")

# Doesn't require a loop
async def event_loop():
    group_info = await base_group.Membership.get() # Uses the id specified in Base_Group
    print(group_info) # Prints group info to console

# Condense these calls
loop = asyncio.get_event_loop()
loop.run_until_complete(event_loop())
loop.close()
```
Into something far less consuming:
```python
from Pyblox.pyblox3 import Groups_v1

# Instance your group as a variable
base_group = Groups_v1(groupid="GROUPID")

group_info = await base_group.Membership.get() # Uses the id specified in Base_Group
print(group_info) # Prints group info or returned error type to console
```
Let me know what you think or if you have any other questions.

**Comment by sbhadr** [comment]
This issue has been improved / corrected in https://github.com/RbxAPI/Pyblox/compare/afb300933ab6...dc5448a3f750 .
